! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert
! #terralith:skylands > null

! ------------------ REPLACED -------------------

"biomeswevegone:dead_sea" > "biomeswevegone:lush_stacks"


! ------------------ DELETED -----------------------

"terralith:alpha_islands_winter" > null
"terralith:alpha_islands" > null
"regions_unexplored:alpha_grove" > null