name = "Aerial Create Guns 'n Dragons (Light)"
author = "GeniusArt, HooMkA, nei3vst4n"
version = "0.7.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c82907f65392d16d4e50fc1f8476c61b9336b6798d53ea34fd54a834d2ffa48"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = ["1.21.1"]
