name = "Aerial Create Guns 'n Dragons (Light)"
author = "GeniusArt, HooMkA, nei3vst4n"
version = "0.7.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "008185bc33a2022076e3241059351bf750d515c7de286d853de7010f88f7e836"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = ["1.21.1"]
