name = "Aerial Create Guns 'n Dragons (Light)"
author = "GeniusArt, HooMkA, nei3vst4n"
version = "0.7.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cb1b01087a67bdf202e5161e14f053a48a417c524ce139f16c5e5677a6209d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = ["1.21.1"]
